name: LunaChatProxySync
version: '1.0-SNAPSHOT'
main: me.tksn.lunaChatProxySync.LunaChatProxySync
api-version: '1.21'
authors: [ 'xkf_' ]
depend:
  - 'LunaChat'
  - 'LuckPerms'
commands:
  lcps:
    description: メインコマンド
    usage: /lcps <reload|help>
    permission: lcps.use
    permission-message: "§cYou don't have permissions to execute this command"
permissions:
  lpcs.use:
    description: メインコマンドの権限
    default: op