name: LunaChatProxySync
version: '1.0-SNAPSHOT'
main: me.tksn.lunaChatProxySync.LunaChatProxySync
api-version: '1.21'
authors: [ 'xkf_' ]
depend:
  - 'LunaChat'
softdepend:
  - 'LuckPerms'
load: POSTWORLD
commands:
  lcps:
    description: メインコマンド
    usage: /lcps <reload|help>
    permission: lcps.use
    permission-message: "§cYou don't have permissions to execute this command"
  tell:
    description: Cross-server tell command
    usage: /<command> <player> <message>
    aliases:
      - t
    permission: lcps.tell
  message:
    description: Cross-server message command
    usage: /<command> <player> <message>
    aliases:
      - msg
      - m
    permission: lcps.message
  reply:
    description: Cross-server message command
    usage: /<command> [<message>]
    aliases:
      - r
    permission: lcps.reply
permissions:
  lcps.use:
    description: メインコマンドの権限
    default: op
  lcps.tell:
    default: true
  lcps.message:
    default: true
  lcps.reply:
    default: true